--- 
clone: 
  depth: 1
kind: pipeline
name: azrimPipeline
steps:
- name: building
  image: fadlyas/kernel_dockerfile
  environment:
    bot_token:
      from_secret: TOKEN
    chat_id:
      from_secret: CHATID
  commands:
  - ./build