#!/bin/bash

export KERNELNAME=DEAGLE

export LOCALVERSION=TESTING

export KBUILD_BUILD_USER=builder

export KBUILD_BUILD_HOST=deagle

export TOOLCHAIN=clang

export DEVICES=surya


source helper

gen_toolchain

send_msg "Start building..."


START=$(date +"%s")

for i in ${DEVICES//,/ }
do
	build ${i}
done

END=$(date +"%s")

DIFF=$(( END - START ))

send_msg "Build complete in $((DIFF / 60))m $((DIFF % 60))s"